//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheet.GUI.SheetServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SheetServiceReference.IBLLService")]
    public interface IBLLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLLService/GetNotes", ReplyAction="http://tempuri.org/IBLLService/GetNotesResponse")]
        Sheet.BLLService.Entities.Note[] GetNotes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLLService/GetNotes", ReplyAction="http://tempuri.org/IBLLService/GetNotesResponse")]
        System.Threading.Tasks.Task<Sheet.BLLService.Entities.Note[]> GetNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLLService/GetNotesByLabel", ReplyAction="http://tempuri.org/IBLLService/GetNotesByLabelResponse")]
        Sheet.BLLService.Entities.Note[] GetNotesByLabel(Sheet.BLLService.Entities.Label label);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLLService/GetNotesByLabel", ReplyAction="http://tempuri.org/IBLLService/GetNotesByLabelResponse")]
        System.Threading.Tasks.Task<Sheet.BLLService.Entities.Note[]> GetNotesByLabelAsync(Sheet.BLLService.Entities.Label label);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLLService/LoadNote", ReplyAction="http://tempuri.org/IBLLService/LoadNoteResponse")]
        Sheet.BLLService.Entities.Note LoadNote(Sheet.BLLService.Entities.Note note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLLService/LoadNote", ReplyAction="http://tempuri.org/IBLLService/LoadNoteResponse")]
        System.Threading.Tasks.Task<Sheet.BLLService.Entities.Note> LoadNoteAsync(Sheet.BLLService.Entities.Note note);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBLLServiceChannel : Sheet.GUI.SheetServiceReference.IBLLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLLServiceClient : System.ServiceModel.ClientBase<Sheet.GUI.SheetServiceReference.IBLLService>, Sheet.GUI.SheetServiceReference.IBLLService {
        
        public BLLServiceClient() {
        }
        
        public BLLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sheet.BLLService.Entities.Note[] GetNotes() {
            return base.Channel.GetNotes();
        }
        
        public System.Threading.Tasks.Task<Sheet.BLLService.Entities.Note[]> GetNotesAsync() {
            return base.Channel.GetNotesAsync();
        }
        
        public Sheet.BLLService.Entities.Note[] GetNotesByLabel(Sheet.BLLService.Entities.Label label) {
            return base.Channel.GetNotesByLabel(label);
        }
        
        public System.Threading.Tasks.Task<Sheet.BLLService.Entities.Note[]> GetNotesByLabelAsync(Sheet.BLLService.Entities.Label label) {
            return base.Channel.GetNotesByLabelAsync(label);
        }
        
        public Sheet.BLLService.Entities.Note LoadNote(Sheet.BLLService.Entities.Note note) {
            return base.Channel.LoadNote(note);
        }
        
        public System.Threading.Tasks.Task<Sheet.BLLService.Entities.Note> LoadNoteAsync(Sheet.BLLService.Entities.Note note) {
            return base.Channel.LoadNoteAsync(note);
        }
    }
}
